# Generated by Django 4.1 on 2022-09-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dcl',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Dcl',
        ),
    ]
