# Generated by Django 4.1 on 2022-09-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0002_task_dcl_delete_dcl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2.task')),
            ],
        ),
        migrations.CreateModel(
            name='Viga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('length', models.IntegerField()),
                ('angle', models.IntegerField()),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigas', to='project2.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_start', models.BooleanField()),
                ('value', models.IntegerField()),
                ('viga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='project2.viga')),
            ],
        ),
        migrations.CreateModel(
            name='Fuerza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_start', models.BooleanField()),
                ('angle', models.IntegerField()),
                ('value', models.IntegerField()),
                ('viga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuerzas', to='project2.viga')),
            ],
        ),
        migrations.CreateModel(
            name='Apoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_start', models.BooleanField()),
                ('tipo', models.IntegerField()),
                ('viga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoyos', to='project2.viga')),
            ],
        ),
    ]
