# Generated by Django 4.1 on 2022-09-13 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0003_diagram_viga_momento_fuerza_apoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram', to='project2.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
