# Generated by Django 4.1 on 2022-09-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0004_alter_diagram_task_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyo',
            name='viga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoyos', to='project2.viga'),
        ),
        migrations.AlterField(
            model_name='fuerza',
            name='value',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='fuerza',
            name='viga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuerzas', to='project2.viga'),
        ),
        migrations.AlterField(
            model_name='momento',
            name='viga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='project2.viga'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viga',
            name='angle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viga',
            name='diagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vigas', to='project2.diagram'),
        ),
    ]
